# ---------------------------------------------------------------------------
# configure.ps1 - writes every config file with your own paths
#
# mpv treats ":" as its option separator, so a Windows path can't go into
# --vf as-is. It needs the length-prefixed escape %N%path, where N is the
# exact character count. Getting N wrong fails silently: the filter simply
# never loads. This script works it out for you.
#
# Usage:
#   .\configure.ps1 -Engine "G:\Tools\mpv-rife" -Stremio "G:\Tools\stremio-community"
# ---------------------------------------------------------------------------

param(
    [Parameter(Mandatory = $true)]
    [string]$Engine,     # folder holding mpv\, vs\ and interpolate.vpy

    [string]$Stremio,    # Stremio Community folder (optional)

    [int]$BufferedFrames = 2
)

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot

function WriteUtf8($path, $text) {
    # Set-Content -Encoding UTF8 on PowerShell 5.1 prepends a BOM, which
    # pollutes .conf and .lua files. This writes clean UTF-8.
    $utf8 = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($path, $text, $utf8)
}

function Require($path, $what) {
    if (-not (Test-Path $path)) { throw "Could not find $what at: $path" }
}

$Engine = (Resolve-Path $Engine).Path.TrimEnd('\')
Require "$Engine\interpolate.vpy" "interpolate.vpy"
Require "$Engine\vs\Lib\site-packages\vapoursynth\vsscript.dll" "VapourSynth"

# mpv wants forward slashes, even on Windows.
$vpy = "$Engine\interpolate.vpy" -replace '\\', '/'
$filter = "vapoursynth=file=%$($vpy.Length)%${vpy}:buffered-frames=$BufferedFrames"

Write-Host "Script path      : $vpy"
Write-Host "Length (the N in the escape): $($vpy.Length)"
Write-Host "Filter line      : vf=$filter"
Write-Host ""

function WriteConf($dest, $extras) {
    $lines = @()
    $lines += "# Generated by tools\configure.ps1 - don't hand-edit the path:"
    $lines += "# the number after % is the path length and has to match."
    $lines += $extras
    $lines += ""
    $lines += "vf=$filter"
    $lines += ""
    $lines += "# VapourSynth needs the frames in system memory, not on the GPU."
    $lines += "hwdec=auto-copy"
    $lines += ""
    $lines += "# The filter already delivers real 60fps; mpv's own"
    $lines += "# interpolation only gets in the way."
    $lines += "interpolation=no"
    $lines += ""
    $lines += "# Follow the monitor's true refresh rate and resample audio to"
    $lines += "# match. This is what stops the audio from drifting."
    $lines += "video-sync=display-resample"
    WriteUtf8 $dest (($lines -join "`r`n") + "`r`n")
    Write-Host "wrote: $dest"
}

function WriteInput($dest) {
    $lines = @(
        "# The filter string must be IDENTICAL to the one in mpv.conf, or",
        "# toggle will add a second filter instead of removing the active one.",
        "CTRL+i vf toggle $filter ; show-text `"Interpolation: toggled`" 2000",
        "CTRL+d show-text `"Dropped: `${frame-drop-count} | Output FPS: `${estimated-vf-fps} | Audio delay: `${audio-delay}s`" 4000",
        "",
        "# Fine audio sync, 20 ms per press.",
        "ALT+RIGHT add audio-delay 0.020 ; show-text `"Audio delay: `${audio-delay}s`" 1500",
        "ALT+LEFT  add audio-delay -0.020 ; show-text `"Audio delay: `${audio-delay}s`" 1500",
        "ALT+DOWN  set audio-delay 0 ; show-text `"Audio delay: reset`" 1500"
    )
    WriteUtf8 $dest (($lines -join "`r`n") + "`r`n")
    Write-Host "wrote: $dest"
}

function WriteLua($dest) {
    $template = Get-Content "$root\stremio\scripts\interpolation.lua" -Raw -Encoding UTF8
    # replace only the filter line, leaving the rest of the script intact
    $template = [regex]::Replace(
        $template,
        '(?m)^\s*"vapoursynth=file=.*?"$',
        "  `"$filter`"")
    New-Item -ItemType Directory -Force -Path (Split-Path $dest) | Out-Null
    WriteUtf8 $dest $template
    Write-Host "wrote: $dest"
}

# --- standalone mpv --------------------------------------------------------
$mpvConfig = "$Engine\mpv\portable_config"
if (Test-Path "$Engine\mpv\mpv.exe") {
    New-Item -ItemType Directory -Force -Path "$mpvConfig\scripts" | Out-Null
    $mpvExtras = @(
        "vo=gpu-next",
        "gpu-api=vulkan",
        "profile=high-quality",
        "",
        "# YouTube: skip AV1. Cards before RDNA2 / RTX 30 have no hardware",
        "# decoder for it, so AV1 would land on the CPU that MVTools is",
        "# already using. VP9 and H.264 decode in hardware instead.",
        "# Also capped at 1080p, since the filter skips anything wider.",
        "ytdl-format=bestvideo[vcodec!*=av01][height<=?1080]+bestaudio/best[height<=?1080]"
    )
    WriteConf "$mpvConfig\mpv.conf" $mpvExtras
    WriteInput "$mpvConfig\input.conf"
    WriteLua "$mpvConfig\scripts\interpolation.lua"
} else {
    Write-Host "standalone mpv not found at $Engine\mpv - skipping"
}

# --- Stremio ---------------------------------------------------------------
if ($Stremio) {
    $Stremio = (Resolve-Path $Stremio).Path.TrimEnd('\')
    Require "$Stremio\stremio-shell-ng.exe" "Stremio Community"
    if ((Test-Path "$Stremio\mpv.conf") -and
        -not (Test-Path "$Stremio\mpv.conf.original")) {
        Copy-Item "$Stremio\mpv.conf" "$Stremio\mpv.conf.original"
        Write-Host "backup: mpv.conf.original"
    }
    WriteConf "$Stremio\mpv.conf" @("log-file=mpv.log", "vo=gpu-next", "gpu-context=d3d11")
    WriteInput "$Stremio\input.conf"
    WriteLua "$Stremio\scripts\interpolation.lua"

    $bat = @"
@echo off
REM ALWAYS launch through this file. Starting the .exe directly leaves mpv
REM unable to find VapourSynth: the filter fails and no video appears -
REM you get audio only.
cd /d "%~dp0"
set "VSSCRIPT_PATH=$Engine\vs\Lib\site-packages\vapoursynth\vsscript.dll"
set "PATH=$Engine\vs;$Engine\vs\Lib\site-packages\vapoursynth;%PATH%"
start "" "%~dp0stremio-shell-ng.exe" %*
"@
    WriteUtf8 "$Stremio\Stremio-60fps.bat" $bat
    Write-Host "wrote: $Stremio\Stremio-60fps.bat"
}

Write-Host ""
Write-Host "Done. Launch Stremio through Stremio-60fps.bat." -ForegroundColor Green
